### ISSUE TITLE
NPE while converting OPA response

### ISSUE THREAD

**Issue by udaraliyanage** [jferrater/opa-data-filter-mongo-demo#5]
I am trying out opa-data-filter-demo. OPA server is setup locally
I am getting below error when I try to access `http://localhost:8081/pets`

Assuming the OPA response is not correct I directly hit OPA` POST http://localhost:8181/v1/compile`. OPA gave below response

**OPA Response**

`{
    "result": {
        "queries": [
            [
                {
                    "index": 0,
                    "terms": [
                        {
                            "type": "ref",
                            "value": [
                                {
                                    "type": "var",
                                    "value": "eq"
                                }
                            ]
                        },
                        {
                            "type": "string",
                            "value": "alice"
                        },
                        {
                            "type": "ref",
                            "value": [
                                {
                                    "type": "var",
                                    "value": "data"
                                },
                                {
                                    "type": "string",
                                    "value": "pets"
                                },
                                {
                                    "type": "var",
                                    "value": "$02"
                                },
                                {
                                    "type": "string",
                                    "value": "owner"
                                }
                            ]
                        }
                    ]
                },
                {
                    "index": 1,
                    "terms": {
                        "type": "ref",
                        "value": [
                            {
                                "type": "var",
                                "value": "data"
                            },
                            {
                                "type": "string",
                                "value": "pets"
                            },
                            {
                                "type": "var",
                                "value": "$02"
                            }
                        ]
                    }
                }
            ]
        ]
    }
}`

**Error message**
`{
  "query" : "data.petclinic.authz.allow = true",
  "input" : {
    "path" : [ "pets" ],
    "method" : "GET",
    "subject" : {
      "user" : "alice",
      "attributes" : {
        "organization" : "SOMA"
      }
    }
  },
  "unknowns" : [ "data.pets" ]
}

                ����������������������������2021-01-29 16:23:51,671 INFO  [http-nio-8081-exec-1] opa.datafilter.core.ast.db.query.service.OpaClientService: Sending partial request to Open Policy Agent server

                ������������org.springframework.http.converter.HttpMessageConversionException: JSON conversion problem: (was java.lang.NullPointerException); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: opa.datafilter.core.ast.db.query.model.response.OpaCompilerResponse["result"]->opa.datafilter.core.ast.db.query.model.response.Result["queries"]->java.util.ArrayList[0]->java.util.ArrayList[1])
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:249)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:228)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:104)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:998)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:981)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:741)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:449)
	at opa.datafilter.core.ast.db.query.service.OpaClientService.getOpaCompilerResponse(OpaClientService.java:100)
	at opa.datafilter.core.ast.db.query.service.OpaClientService.getOpaCompilerApiResponse(OpaClientService.java:90)
	at opa.datafilter.core.ast.db.query.service.OpaClientService.getOpaCompilerApiResponse(OpaClientService.java:81)
	at com.github.jferrater.opadatafilterjpaspringbootstarter.query.QueryService.getTypedQuery(QueryService.java:24)
	at com.github.jferrater.opadatafilterjpaspringbootstarter.repository.OpaDataFilterRepositoryImpl.findAll(OpaDataFilterRepositoryImpl.java:49)
	at com.github.jferrater.opadatafilterjpaspringbootstarter.repository.OpaDataFilterRepositoryImpl.findAll(OpaDataFilterRepositoryImpl.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:371)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:204)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:657)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:621)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:605)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:178)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy108.findAll(Unknown Source)
	at com.example.opadatafilterdemo.service.PetProfileService.getPetProfiles(PetProfileService.java:29)
	at com.example.opadatafilterdemo.controller.PetProfileController.getLovelyPets(PetProfileController.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)`

**Comment by jferrater** [comment]
Thanks for reporting. Looks like this project was outdated. I'll fix it.

**Comment by mranjit** [comment]
Hello @jferrater this fix is not updated in master . Will it be possible to merge this fix ?
I was facing the same issue with OPA 0.35 version. After the upgrade to com.github.jferrater:opa-datafilter-mongo-spring-boot-starter:0.5.1 , this issue got fixed but I was getting another NPE issue . 
After going through the code , I found due to above change , now one of the Predicate looks like 
Predicate(index=2, terms=[]) . Due to this one of the SqlPredicate value  in AstToMongoDBQuery is null and eventually it throws NPE.
When I overrode the class in my project and made a null check on SqlPredicate in chainCriteriaByAndOperator method , it works fine .
If you are fine , I can raise a PR for the same .
Thanks again for the great work !!!

**Comment by jferrater** [comment]
Hello @mranjit , of course you can create a PR. Just return from vacation. Thanks.
